id: I44A242DA
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:30:55.744875
last_modified: 2023-01-04 11:30:55.744891
source_metadata:
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
bases:
  '1941':
    title: Prayer for the Long Life of Soktsé Rinpoche
    base_file: 1941.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
